run:
  timeout: 5m
  tests: true

linters:
  enable-all: true
  disable:
    - gci

linters-settings:
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithStack(
